### ISSUE TITLE
question(s): creating sub-commands on runtime; command.Invoke() row in the code

### ISSUE THREAD

**Issue by rychlym** [natemcmaster/CommandLineUtils#33] opened 2017-12-27 20:47 UTC
Hi,
1) I have already defined  couple of classes similar in Subcommands sample. (I use the inheritance).
 
Now, I wonder, whether it is possible to add a code in one of that already defined  Sub-commands class, which will create inner sub-comands  programmatically. (I face to a list of sub-comands definition, which comes from an external service, which could continuously grow, I would like to map that metadata to generate the CommandLineUtils sub-command structure on the fly). 
From other point of view -  is it possible to combine the attribute SubCommand with a code for defining of sub-commands?

2) it might relate to 1) I am not so sure though, - I little investigated the source code, I wonder about the place   command.Invoke(); in Bind(IConsole console, string[] args) method of the  ReflectionAppBuilder<TTarget> class. What is  the purpose of calling it? It sounds to me the command has already been processed at that time, while  it is going to be is invoked  further in the case of being matched as the target command. 
Could  you, please, give me a little code snippet example,  how to inject a code from such a command class to be invoked at that "command.Invoke()" time?

TIA,
Mojmir

**Comment by natemcmaster** [comment] 2017-12-28 06:10
>  is it possible to combine the attribute SubCommand with a code for defining of sub-commands?

1. At the moment, dynamically generating subcommands is only possible using the builder API. For example, you could do this.

```c#
class Program
{
    public static int Main(string[] args)
    {
        var app = new CommandLineApplication
        {
            Name = "my-app",
        };

        var verbs = ExternalService.GetSubcommands();

        foreach (var verb in verbs)
        {
            app.Command(verb.Name, subcmd =>
            {
                foreach (var option in verb.Options)
                {
                    subcmd.Option(option.Template, option.Description, option.Type);
                }
            }
        }

        return app.Execute(args);
    }
}
```

2. Short answer: you should define a method named `OnExecute` on your subcommand types.

Samples
https://github.com/natemcmaster/CommandLineUtils/blob/c2499313f4cd64cfba20059528f54f6d87c728b3/samples/HelloWorld.Attributes/Program.cs#L16-L20
https://github.com/natemcmaster/CommandLineUtils/blob/c2499313f4cd64cfba20059528f54f6d87c728b3/samples/Subcommands/Inheritance.cs#L24-L29

Long answer:
`ReflectionAppBuilder` calls `command.Invoke()` as an internal implementation detail. When it does, this is the method that is invoked:

https://github.com/natemcmaster/CommandLineUtils/blob/c2499313f4cd64cfba20059528f54f6d87c728b3/src/CommandLineUtils/Internal/ReflectionAppBuilder.cs#L381-L393

ReflectionAppBuilder builds up a list of "binders" that parse command-line arguments into CLR properties, as discovered via reflection. For example, the binder that takes `--some-value` and converts it to `[Option] public bool SomeValue { get; }` is defined here.

https://github.com/natemcmaster/CommandLineUtils/blob/c2499313f4cd64cfba20059528f54f6d87c728b3/src/CommandLineUtils/Internal/ReflectionAppBuilder.cs#L318-L321

This doesn't actually invoke any user code at this point. This comes later after the binding is done. After binding, the target subcommand type is examined for a method named `OnExecute` or `OnExecuteAsync`, and this is invoked.

https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/CommandLineApplication.Execute.cs#L59-L68

**Comment by rychlym** [comment] 2017-12-29 11:27
1) understood, anyway thanks for the code sample - that can help me 
2) I was  confused with that, I though  ComandLineApplication's OnExecute method is set on some  to the user code and that is only meaning of that method. So that let's me be confused why it is there and it did't  call the  user code which of course would be bad at that time, because calling the user code is made further  (as you mentioned).

(for some detail, I think it is needed to mention the OnExecute is kind of helper-setter of the ComandLineApplication's Invoke property.
https://github.com/natemcmaster/CommandLineUtils/blob/c780b6cb1360e9e1bc4061c4bb7493cfdebf3ac1/src/CommandLineUtils/CommandLineApplication.cs#L355-L370

Now I can see, there is some kind of dynamics behind the ComandLineApplication's Invoke property, which I might not understand completely yet. 
At least, I can see through debug, that it is initialized to ()=>0 in the ComandLineApplication's ctor. and then set to the  ReflectionAppBuilder's OnExecute method (you described above) 
https://github.com/natemcmaster/CommandLineUtils/blob/c780b6cb1360e9e1bc4061c4bb7493cfdebf3ac1/src/CommandLineUtils/Internal/ReflectionAppBuilder.cs#L39-L42

I guess the Invoke properties are then not changed. I think it is would be also good to repeat, we are talking about scenario with sub-commands and attributed API

Do I understand it correctly or is there anything to add to this?

3) I actually did the investigation because I would need to run an "user code" - a kind of logger initialization regardless any target sub-command, but regards the Top (root) command parameter.
That initialization needs to be invoked before calling OnExecute of the target sub command. 
My Idea was to define  an Initialize() method in the Top (root) command, and call it by CommandLineUtils by convention. 
https://github.com/rychlym/CommandLineUtils/blob/bdddb516fb8536d1f44fdfba94451e8f05ca4276/samples/Subcommands/Inheritance.cs#L35-L50

I have forked the repository and added the code doing that. (It is working with synchronous type of Initialize method. I needed also have injected raw command line parameters into the initialize. That all was possible to do with some small internal changes. 

(I don't need it right now and unlikely don't have time, but I can see, it could be extended in the future to support calling initialization 
on the tree path to the target sub command in order and also calling async variant of invoke after clarification how it)
If it seems to worth to you, you can take look at it?? Anyway, there seems to be a different solution mentioned in  https://github.com/natemcmaster/CommandLineUtils/issues/31 prepared by [shovonnn](https://github.com/shovonnn) in the game - it also seems to call a kind of initial user code.

**Comment by natemcmaster** [comment] 2017-12-30 19:56
I think you've got a correct understanding of how things work.

There are some pieces of https://github.com/rychlym/CommandLineUtils/commit/936947ce0d0e94e3f93a744c72a431a3da21ecb0 I'd like to take. For instance, the ability to get the original `string[] args` from the OnExecute method.

I need to think more about the "Initialize" method you are proposing. My initial reaction is that it's not immediately clear that `Git.Initialize` would be invoked when `CommitCommand` is the target subcommand. What if we added something like this instead?

```c#
[Subcommand("commit", typeof(CommitCommand))]
public class Git
{
    public void Initialize()
    {
    }
}

public class CommitCommand
{
    public CommitCommand(Git parent)
    {
        _parent = parent;
    }

    public void OnExecute()
    {
        _parent.Initialize();
    }
}
```

**Comment by natemcmaster** [comment] 2017-12-30 22:10
By the way, this isn't the most obvious feature of this library, but you could already structure an app like this. The `Parent` property on sub command types is automatically set to the parent.
```c#
[Subcommand("commit", typeof(Commit))]
public class Git
{
    public void Initialize()
    {
    }
}

public class Commit
{
    public Git Parent { get; }

    public void OnExecute()
    {
        Parent.Initialize();
    }
}
```

**Comment by rychlym** [comment] 2018-01-02 06:30
Hi,
thanks for your answers. 
I see the Initialize method in the fork as a CommandLineUtils  convention (with a similar  worth like the Parent property wrote about in the last) Problem might be in the naming of it - e.g. that meaning of  the  "Parent is quite obvious. I understand, that  the Initialize might not be so straight forward - "Something from client code, that is called allays at the beginning (within the root command)". I am even also thinking about extending that to:  "Something from client code, that is called allays at the beginning (starting from root with possibility to call at each command node up to the target command)"

I  see that "Initialize call by convention" approach better then using the Parent  properties, because the usage off parent properties leads to a repeatable code inside of the command classes. In case of small amount of command it does not matter. I my case, I have 3 depth tree so the "leaf" commands then would have code like Parent.Parent.Initialize()

I understand, it is not easy to add a change like that to the library. In case your first reaction is not affirmative, you can postpone it. When someone else would need that in the future, you can overtake it.
(currently I am using it in my home purposes project,  (a boiler control command line app in raspberry pi :) ), so I am fine with the  fork, actually it is great that  I am able to  freely do some changes and thanks again for your support.

**Comment by rychlym** [comment] 2018-04-02 20:47
Thanks for informing and please excuse me I haven't found a time for a checking. I have shortly checked  it with today's version by debugging the Convention example. It looks to me very impressive and the calling of the IConvention.Apply seems to be on right time, when parsed arguments/options... are ready to use in the ConventionContext instance. Still I would need for my particular needs the raw version of the arguments - did I skim it or is it possible to be as a part of the library (e.g.  part of convention context) or should I use an own way of injection the raw arguments?

**Comment by rychlym** [comment] 2018-04-03 10:10
I have done further "debug" observations further found that:
1)  IConvention .Apply is called more time before executing a command - perhaps called per all the defined commands - is it so?
2) the ConventionContext's Application.Options is filled only with options defined on place before actual calling of app.Conventions.AddConvention - is it a bug or a feature? 
2a) the possible call of option.HasValue() from the context gives always false at time  IConvention .Apply is called?? It might behaves so from principle as the context is constructed step by step, Could it be possible to do without a big effort,  that the some objects inside of context can give an info they are "fully ready" like giving same results as in time OnExecute  was  running.

I am still curious about topic of defining one time running initialization code with possibility to have parsed options and arguments  results.  (for all the possible commands/options (except help) without any extra plumbing. I tried to put such code to the model constructor and was quite successful - options.HasValue() give correct results. (But it is not so clear - the  time the model is created in the HandleParseResult() method, all the work with parsing is not done yet - so I would rather keep version with my fork, where I have defined an initialization method by convention.

**Comment by natemcmaster** [comment] 2018-04-03 16:03
By design, conventions are used to define the structure of a CommandLineApplication. If you want to run something after the command line application is defined, use [`CommandLineApplication.OnParsingComplete`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?q=CommandLineApplication#McMaster_Extensions_CommandLineUtils_CommandLineApplication_OnParsingComplete_System_Action_McMaster_Extensions_CommandLineUtils_Abstractions_ParseResult__) to add a callback.

If you want to customize how you initialize types by convention, checkout the [https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/Conventions/ConstructorInjectionConvention.cs](ConstructorInjectionConvention). You can disable or override conventions and write your own. This conventions uses [`CommandLineApplication<T>.ModelFactory`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication-1.html?q=ModelFactory#McMaster_Extensions_CommandLineUtils_CommandLineApplication_1_ModelFactory) to customize how the types are created.

**Comment by natemcmaster** [comment] 2018-04-04 15:18
Cool. It sounds to me like your original question has been answered. Ok if I close this issue now?

**Closed** 2018-04-05 04:08 UTC
Labels: question
