### ISSUE TITLE
Argument of Type bool get Parsed Value True/False

### ISSUE THREAD

**Issue by aherrick** [natemcmaster/CommandLineUtils#151] opened 2018-09-11 21:01 UTC
I'm trying to have a basic boolean command argument for my App.

Something like:

`var useLocalDB = inviteUserCmd.Argument<bool>("useLocalDB", "Use Local DB For Debug.").IsRequired().Accepts(x => x.Values("true", "false"));`

When I use `IsRequired` I no longer have access to `ParsedValue`

I'm just looking for the simplest/cleanest way of forcing the user to enter true/false.

**Comment by natemcmaster** [comment] 2018-09-25 16:13
Closing as a duplicate of https://github.com/natemcmaster/CommandLineUtils/issues/131. This issue has been fixed in the source, but has not been released yet. It will be released in 2.3

**Closed by natemcmaster** 2018-09-25 16:13 UTC
