### ISSUE TITLE
Subcommand options not parsed correctly when using RemainingArguments

### ISSUE THREAD

**Issue by cskwrd** [natemcmaster/CommandLineUtils#179] opened 2018-11-16 07:29 UTC
**Describe the bug**
When `public string[] RemainingArguments { get; }` is specified, options that are mixed with args are not parsed correctly.

**To Reproduce**
```csharp
[Command("test-cmd")]
[VersionOptionFromMember("--version", MemberName = nameof(GetVersion))]
[Subcommand(typeof(MySubCommand))]
public class Program : MyCommandBase
{
	public static int Main(string[] args)
	{
		var binBlasterConsoleApp = new CommandLineApplication<Program>();

		binBlasterConsoleApp.Conventions.UseDefaultConventions();

		return binBlasterConsoleApp.Execute(args);
	}

	protected override int OnExecute(CommandLineApplication app)
	{
		// this shows help even if the --help option isn't specified
		app.ShowHelp();
		return 1;
	}

	public override List<string> CreateArgs()
	{
		var args = new List<string>();
		return args;
	}

	private static string GetVersion() => typeof(Program).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;
}

[Command(Name = "subcmd", Description = "Do sub-command things.", ThrowOnUnexpectedArgument = false)]
public class MySubCommand : MyCommandBase
{
	private Program Parent { get; set; }

	public string[] RemainingArguments { get; }

	[Option(Description = "Dump output", Template = "-d")]
	public bool DumpOutput { get; set; }

	public override List<string> CreateArgs()
	{
		var args = Parent.CreateArgs();
		return args;
	}

	protected override int OnExecute(CommandLineApplication cla)
	{
		var args = CreateArgs();

		Console.WriteLine($"{nameof(DumpOutput)}: {DumpOutput}, {nameof(RemainingArguments)}: {ArgumentEscaper.EscapeAndConcatenate(RemainingArguments)}");
		return 0;
	}
}

[HelpOption()]
public abstract class MyCommandBase
{
	public abstract List<string> CreateArgs();

	protected abstract int OnExecute(CommandLineApplication cla);
}
```

**Expected behavior**
```
> subcmd "fileName.txt" -d
DumpOutput: True, RemainingArguments: fileName.txt
```

**Actual behavior**
```
> subcmd "fileName.txt" -d
DumpOutput: False, RemainingArguments: fileName.txt -d
```

**Additional context**
https://github.com/natemcmaster/CommandLineUtils/blob/dface2ab96603ef130f8fbfdff68caf1416ae1af/src/CommandLineUtils/Internal/CommandLineProcessor.cs#L363-L369

**Comment by natemcmaster** [comment] 2018-11-26 01:17
I'm closing this as a duplicate of https://github.com/natemcmaster/CommandLineUtils/issues/171. The behavior you're encountering is by design -- unexpected arguments are handled by stopping the parser at the first unexpected arg, putting everything after into `RemainingArgs`. The request in https://github.com/natemcmaster/CommandLineUtils/issues/171 is to allow for additional options in controlling this behavior.

**Closed by natemcmaster** 2018-11-26 01:17 UTC
