### ISSUE TITLE
A boolean option with a type of SingleValue or SingleOrNoValue should be set to "true" when present

### ISSUE THREAD

**Issue by wlrichards** [natemcmaster/CommandLineUtils#133] opened 2018-08-06 23:57 UTC
The normal convention for a command line option that is a flag is for the flag to be  to be "on" if that argument is present and "not on" when not present i.e. you should not have to specify a value for that option to turn it on

**To Reproduce**
1. Add a CommandOption<bool> with type CommandOption.SingleValue or CommandOption.SingleOrNoValue
2. Run the app and supply the option without a value

**Expected behavior**
I would expect the value of that option to be set to true but it currently gets set to false

**Comment by natemcmaster** [comment] 2018-08-07 00:02
The behavior you're describing is `CommandOption.NoValue`. Why would you expect `SingleValue` to have the same behavior? I can see why you might expect `SingleOrNoValue` and that's probably a bug, but `SingleValue` means you require the user to specify `--name value` or `--name=value`. 

FYI - this looks like a duplicate of https://github.com/natemcmaster/CommandLineUtils/issues/129. Does this comment help explain? https://github.com/natemcmaster/CommandLineUtils/issues/129#issuecomment-409779587

**Comment by natemcmaster** [comment] 2018-08-07 03:17
Can you provide some code to reproduce the error? Also, which kinds of arguments are you passing into the app?

**Comment by natemcmaster** [comment] 2018-08-15 07:10
>  The problem does occur with CommandOption.NoValue as well as CommandOption.SingleOrNoValue.

If you can share repro code to show this problem, I'm happy to re-open and take a closer look.

**Closed by natemcmaster** 2018-08-15 07:10 UTC
Labels: more-info-needed

**Comment by fubar-coder** [comment] 2019-04-16 10:20
I ran into this "problem" too. What I wanted to do was:

```csharp
        [Option("--strip", "Strip comments from the SQL scripts. Default is true.", CommandOptionType.SingleOrNoValue)]
        public bool StripComments { get; set; } = true;
```

Now I expected that I can use `--strip:false` to disable this option while still being able to use `--strip` and the value of `StripComments` should be set to `true`. I know that this is bad practice, but sometimes you have to deal with legacy behaviour.

This is my current workaround:

```csharp
        [Option("--strip", "Strip comments from the SQL scripts. Default is true.", CommandOptionType.SingleOrNoValue)]
        public (bool hasValue, bool? value) StripComments { get; set; }
```

And this is the way I use this option:

```csharp
            StripComments = !cmd.StripComments.hasValue || (cmd.StripComments.value ?? true);
```
