### ISSUE TITLE
Support options with multiple values

### ISSUE THREAD

**Issue by josesimoes** [natemcmaster/CommandLineUtils#311] opened 2019-12-06 16:09 UTC
Hi,

I'm trying to use an option that's supposed to have multiple values, like this:
`--loadHints foo c:\path\to\foo --loadHints bar c:\path\to\bar ` 

Can't find a way to define/parse this. Even tried a custom parser but it seems that it only accepts one value for the option instead of taking everything up to the next separator.

**Comment by natemcmaster** [comment] 2019-12-14 21:38
Currently not supported. You're not the first to ask, though, and I'm not opposed to adding it. I'll mark this as a feature request and "help wanted". I can't promise when I'll get around to this, or even if I'll get around to it at all, but if you're interested in providing a pull request, let me know and we can discuss what an API for this should look like.

**Comment by josesimoes** [comment] 2019-12-16 09:59
Thanks for the feedback. In the end we choose to go through a different path that doesn't require a CLI anymore. So this is not relevant anymore to the project.

PS: congrats on this awesome library!! 👏 😄

**Comment by natemcmaster** [comment] 2020-01-05 21:42
Closing as a duplicate of #229.

**Closed by natemcmaster** 2020-01-05 21:42 UTC
Labels: enhancement, help wanted
